name: Lint code base

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint code base
    uses: ./.github/workflows/linter.yml
