name: Lint code base

on:
  workflow_call:
    inputs:
      default-branch:
        description: The default branch of the repository
        type: string
        required: false
        default: main
      filter-regex-exclude:
        description: Regex for files to exclude from linting
        type: string
        required: false
      validate-css:
        description: Run stylelint for CSS
        type: string
        required: false
        default:
      validate-dockerfile:
        description: Run hadolint for dockerfiles
        type: string
        required: false
        default:
      validate-json:
        description: Run eslint for JSON
        type: string
        required: false
        default:
      validate-lua:
        description: Run luacheck
        type: string
        required: false
        default:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: Lint code base
        uses: github/super-linter/slim@v4.9.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          FILTER_REGEX_EXCLUDE: ${{ inputs.filter-regex-exclude }}

          # Always run these
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSCPD: true
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true

          # Optional linters
          VALIDATE_CSS: ${{ inputs.validate-css }}
          VALIDATE_DOCKERFILE_HADOLINT: ${{ inputs.validate-dockerfile }}
          VALIDATE_JSON: ${{ inputs.validate-json }}
          VALIDATE_LUA: ${{ inputs.validate-lua }}
