name: Lint code base

on:
  workflow_call:
    inputs:
      default-branch:
        description: The default branch of the repository
        type: string
        required: false
        default: main
      filter-regex-exclude:
        description: Regex for files to exclude from linting
        type: string
        required: false
      validate-css:
        description: Run stylelint for CSS
        type: string
        required: false
        default:
      validate-dockerfile:
        description: Run hadolint for dockerfiles
        type: string
        required: false
        default:
      validate-json:
        description: Run eslint for JSON
        type: string
        required: false
        default:
      validate-lua:
        description: Run luacheck
        type: string
        required: false
        default:

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-22.04
    # env:
    #   FETCH_DEPTH: 1

    steps:
    #   - name: Override fetch depth for PRs from forks
    #     if: github.event.pull_request.head.repo.fork
    #     run: |
    #       echo FETCH_DEPTH=0 >> "$GITHUB_ENV"

      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: >-
            ${{ github.event.pull_request.head.repo.fork && '0' || 1 }}
          show-progress: false

      - name: Fetch default style files
        env:
          css: ${{ inputs.validate-css }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mkdir --parents .github/linters
          fnames=('.markdown-lint.yml' '.yaml-lint.yml')
          if [[ $css == 'true'  ]]; then
              fnames+=('.stylelintrc.json')
          fi

          for fname in "${fnames[@]}"; do
              if [[ -r .github/linters/$fname ]]; then
                  continue
              fi

              echo "Fetching default $fname..." >&2

              gh api \
                  "repos/bewuethr/workflows/contents/.github/linters/$fname" \
                  --jq '.content | @base64d' \
                  > ".github/linters/$fname"
          done

          fname='.editorconfig'
          if [[ -r $fname ]]; then
              exit 0
          fi

          echo "Fetching default $fname..." >&2

          gh api "repos/bewuethr/workflows/contents/$fname" \
              --jq '.content | @base64d' \
              > "$fname"

      - name: Lint code base
        uses: super-linter/super-linter/slim@v5.7.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          FILTER_REGEX_EXCLUDE: ${{ inputs.filter-regex-exclude }}

          # Always run these
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSCPD: true
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true

          # Optional linters
          VALIDATE_CSS: ${{ inputs.validate-css }}
          VALIDATE_DOCKERFILE_HADOLINT: ${{ inputs.validate-dockerfile }}
          VALIDATE_JSON: ${{ inputs.validate-json }}
          VALIDATE_LUA: ${{ inputs.validate-lua }}
